export * from './schema/types.js';
export * from './schema/constants.js';
export * from './schema/validators.js';
export * from './graph/store.js';
export * from './graph/query.js';
export { normalizeGraph } from './graph/normalize.js';
export { mergeSubgraphs } from './graph/merge-subgraphs.js';
export type { NormalizationReport } from './graph/normalize.js';
export type { MergeResult } from './graph/merge-subgraphs.js';
export * from './llm/client.js';
export * from './agents/base.js';
export * from './orchestrator/runner.js';
export * from './watcher/watcher.js';
export * from './utils/fs.js';
export * from './utils/embedding-search.js';
export { calcHealthGrade, gradeColor } from './utils/health-grade.js';
export { appendSnapshot, loadHistory } from './utils/history.js';
export { lcsLength, lcsSimilarity, structuralFingerprint } from './utils/similarity.js';
export { generateMermaid } from './utils/mermaid.js';
export type { HealthGrade, HistorySnapshot, SecurityWarning, SecurityCategory, DetectedPattern } from './schema/types.js';
