import { describe, it, expect } from 'vitest';
import { readFileSync, readdirSync, existsSync, statSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { join, resolve } from 'node:path';
import { load as parseYaml } from 'js-yaml';

// Repo root is three levels up from packages/cli/tests
const REPO_ROOT = resolve(__dirname, '../../..');

// The canonical 11-skill set shared by every platform surface
const SKILLS = [
  'sprang',
  'sprang-analyze',
  'sprang-chat',
  'sprang-diff',
  'sprang-domain',
  'sprang-explain',
  'sprang-health',
  'sprang-knowledge',
  'sprang-onboard',
  'sprang-team',
  'sprang-why',
].sort();

const MCP_TOOLS = [
  'sprang_query',
  'sprang_node',
  'sprang_diff_impact',
  'sprang_tour',
  'sprang_domain',
  'sprang_health',
  'sprang_why',
  'sprang_annotate',
  'sprang_respond',
];

/** `skills/` is canonical; these are generated by scripts/sync-agent-assets.mjs. */
const GENERATED_SKILL_TREES = ['.devin/skills', '.claude/skills'];

function readJson(relPath: string): any {
  return JSON.parse(readFileSync(join(REPO_ROOT, relPath), 'utf-8'));
}

function listDirNames(relPath: string): string[] {
  return readdirSync(join(REPO_ROOT, relPath)).sort();
}

/** Parse the YAML frontmatter block of a SKILL.md (between the leading --- fences). */
function parseFrontmatter(content: string): Record<string, unknown> | null {
  if (!content.startsWith('---')) return null;
  const end = content.indexOf('\n---', 3);
  if (end === -1) return null;
  const parsed = parseYaml(content.slice(3, end));
  return typeof parsed === 'object' && parsed !== null ? (parsed as Record<string, unknown>) : null;
}

describe('manifests', () => {
  const MANIFESTS = [
    '.devin-plugin/plugin.json',
    '.claude-plugin/plugin.json',
    '.claude-plugin/marketplace.json',
    'plugin.json',
    '.devin/mcp_config.json',
    '.devin/hooks.v1.json',
    '.claude/settings.json',
    '.mcp.json',
    '.vscode/mcp.json',
  ];

  it.each(MANIFESTS)('%s parses as JSON', (relPath) => {
    expect(() => readJson(relPath)).not.toThrow();
  });

  it('all three plugin manifests share the CLI package version and name "sprang"', () => {
    const cliVersion = readJson('packages/cli/package.json').version;
    expect(cliVersion).toBeTruthy();
    // Devin reads .devin-plugin/, Claude reads .claude-plugin/, Copilot reads the
    // root plugin.json. All three can coexist because the locations don't collide.
    for (const relPath of ['.devin-plugin/plugin.json', '.claude-plugin/plugin.json', 'plugin.json']) {
      const manifest = readJson(relPath);
      expect(manifest.name, `${relPath} name`).toBe('sprang');
      expect(manifest.version, `${relPath} version`).toBe(cliVersion);
    }
  });

  it('the Copilot manifest points at the canonical skills/ directory', () => {
    const manifest = readJson('plugin.json');
    expect(typeof manifest.skills).toBe('string');
    const skillsDir = resolve(REPO_ROOT, manifest.skills);
    expect(existsSync(skillsDir), `skills dir ${skillsDir}`).toBe(true);
    for (const skill of SKILLS) {
      expect(existsSync(join(skillsDir, skill, 'SKILL.md')), `${skill}/SKILL.md`).toBe(true);
    }
  });

  it('the Devin manifest points at skills/ and expands ${PLUGIN_ROOT} to the MCP server', () => {
    const manifest = readJson('.devin-plugin/plugin.json');
    expect(Array.isArray(manifest.skills)).toBe(true);
    for (const skillPath of manifest.skills) {
      const resolved = resolve(REPO_ROOT, skillPath);
      expect(existsSync(resolved), `${skillPath} should resolve from repo root`).toBe(true);
      expect(statSync(resolved).isDirectory()).toBe(true);
    }
    const serverPath = manifest.mcpServers.sprang.args[0].replace('${PLUGIN_ROOT}', REPO_ROOT);
    expect(serverPath).toContain('packages/mcp/dist/server.js');
    expect(existsSync(serverPath), `${serverPath} should exist (repo must be built)`).toBe(true);
  });

  it('the Claude manifest expands ${CLAUDE_PLUGIN_ROOT} to the MCP server', () => {
    const marketplace = readJson('.claude-plugin/marketplace.json');
    expect(marketplace.plugins[0].source).toBe('./');

    const manifest = readJson('.claude-plugin/plugin.json');
    const serverPath = manifest.mcpServers.sprang.args[0].replace('${CLAUDE_PLUGIN_ROOT}', REPO_ROOT);
    expect(serverPath).toContain('packages/mcp/dist/server.js');
    expect(existsSync(serverPath), `${serverPath} should exist (repo must be built)`).toBe(true);
  });

  it('every MCP config references the built server and sets SPRANG_ROOT', () => {
    expect(existsSync(join(REPO_ROOT, 'packages/mcp/dist/server.js'))).toBe(true);
    for (const relPath of ['.devin/mcp_config.json', '.mcp.json', '.vscode/mcp.json']) {
      const manifest = readJson(relPath);
      // .vscode/mcp.json uses VS Code's "servers" key; the others use "mcpServers"
      const server = (manifest.mcpServers ?? manifest.servers)?.sprang;
      expect(server, `${relPath} should define a sprang server`).toBeTruthy();
      expect(server.args?.[0], `${relPath} args`).toContain('packages/mcp/dist/server.js');
      expect(server.env?.SPRANG_ROOT, `${relPath} env.SPRANG_ROOT`).toBeTruthy();
    }
  });

  it('never references ${workspaceFolder} in an MCP config', () => {
    // It looks supported and is not. Devin's MCP loader treats ${NAME} as an
    // environment variable lookup (only ${env:VAR} / ${file:/path} are real),
    // so an unset `workspaceFolder` is substituted with an EMPTY STRING:
    //   [MCP] environment variable 'workspaceFolder' is not set; substituting empty string
    // In `args` that means node opens a literal "/packages/mcp/dist/server.js"
    // and the server never starts. In `env` it means SPRANG_ROOT="" and every
    // graph path resolves against the filesystem root. Both fail silently —
    // the tools simply vanish from the session. The server is spawned with the
    // workspace as cwd, so "." is the correct value.
    for (const relPath of ['.devin/mcp_config.json', '.vscode/mcp.json', '.mcp.json']) {
      const manifest = readJson(relPath);
      const server = (manifest.mcpServers ?? manifest.servers).sprang;
      expect(JSON.stringify(server), `${relPath} must not use \${workspaceFolder}`).not.toContain(
        'workspaceFolder',
      );
      expect(server.env.SPRANG_ROOT, `${relPath} SPRANG_ROOT`).toBeTruthy();
    }
  });

  it('no Windsurf-era surface survives', () => {
    for (const gone of [
      '.windsurf',
      '.claude/commands',
      '.copilot-plugin',
      '.devin/hooks.json',
      'packages/cascade-messaging',
      'cascade-messaging-0.1.0.vsix',
    ]) {
      expect(existsSync(join(REPO_ROOT, gone)), `${gone} should be removed in v0.3.0`).toBe(false);
    }
  });

  it('wires the dashboard-question hooks that deliver into a live Devin session', () => {
    // This replaced the bridge extension. The extension could only reach the
    // chat panel — a new Cascade conversation with none of the session's
    // context — and, being instant, it beat the hook every time when both were
    // installed, so questions were silently answered by the wrong agent.
    const cfg = readJson('.devin/hooks.v1.json');
    const wired = ['Stop', 'UserPromptSubmit'].filter((event) =>
      (cfg[event] ?? []).some((entry: any) =>
        (entry.hooks ?? []).some((h: any) => String(h.command).includes('dashboard-question')),
      ),
    );
    expect(wired, 'both Stop and UserPromptSubmit should deliver questions').toEqual([
      'Stop',
      'UserPromptSubmit',
    ]);
    for (const script of ['stop-dashboard-question.sh', 'user-prompt-dashboard-question.sh']) {
      const path = join(REPO_ROOT, '.devin/hooks', script);
      expect(existsSync(path), `${script} should exist`).toBe(true);
      expect(statSync(path).mode & 0o111, `${script} should be executable`).not.toBe(0);
    }
  });

  it('ships no chat-injection extension', () => {
    // Deliberately removed: see the hook test above.
    for (const gone of ['sprang-devin-bridge-0.3.0.vsix', 'cascade-messaging-0.1.0.vsix']) {
      expect(existsSync(join(REPO_ROOT, gone)), `${gone} should not be committed`).toBe(false);
    }
  });
});

describe('skills', () => {
  it('skills/ contains exactly the canonical 11 folders', () => {
    expect(listDirNames('skills')).toEqual(SKILLS);
  });

  it.each(SKILLS)('%s has valid frontmatter and is self-contained', (skill) => {
    const path = join(REPO_ROOT, 'skills', skill, 'SKILL.md');
    expect(existsSync(path), `${path} should exist`).toBe(true);
    const content = readFileSync(path, 'utf-8');

    const fm = parseFrontmatter(content);
    expect(fm, `${skill} should have YAML frontmatter`).not.toBeNull();
    expect(fm!['name'], `${skill} frontmatter name`).toBe(skill);
    expect(typeof fm!['description'], `${skill} description type`).toBe('string');
    expect(String(fm!['description']), `${skill} description`).toContain('Use when');
    // argument-hint must be a plain string; a YAML list breaks completion rendering.
    if ('argument-hint' in fm!) {
      expect(typeof fm!['argument-hint'], `${skill} argument-hint must be a string`).toBe('string');
    }

    // The instructions used to live in .windsurf/workflows/, which only Windsurf
    // loaded — every other platform got a stub pointing at a file it never had.
    expect(content, `${skill} must not reference the removed .windsurf tree`).not.toMatch(/\.windsurf/);
    const body = content.slice(content.indexOf('\n---', 3) + 4);
    expect(body.trim().length, `${skill} body should be substantive`).toBeGreaterThan(400);
  });

  it('the two long procedures ship a REFERENCE.md alongside the skill', () => {
    for (const skill of ['sprang-analyze', 'sprang-knowledge']) {
      const ref = join(REPO_ROOT, 'skills', skill, 'REFERENCE.md');
      expect(existsSync(ref), `${skill}/REFERENCE.md should exist`).toBe(true);
      const skillMd = readFileSync(join(REPO_ROOT, 'skills', skill, 'SKILL.md'), 'utf-8');
      expect(skillMd, `${skill} SKILL.md should point at REFERENCE.md`).toContain('REFERENCE.md');
    }
  });

  it('sprang-analyze ships the merge.py helper', () => {
    expect(existsSync(join(REPO_ROOT, 'skills/sprang-analyze/scripts/merge.py'))).toBe(true);
  });

  it('no skill instructs an invalid edge type', () => {
    // `tests` is not in EDGE_TYPES; emitting it produced unloadable graphs.
    for (const skill of SKILLS) {
      for (const file of ['SKILL.md', 'REFERENCE.md']) {
        const path = join(REPO_ROOT, 'skills', skill, file);
        if (!existsSync(path)) continue;
        const content = readFileSync(path, 'utf-8');
        expect(content, `${skill}/${file} must not instruct a \`tests\` edge`).not.toMatch(/`tests`/);
        expect(content, `${skill}/${file} must not template "layer": null`).not.toMatch(/"layer":\s*null/);
      }
    }
  });
});

describe('generated agent assets', () => {
  it.each(GENERATED_SKILL_TREES)('%s mirrors the canonical skills/ tree', (tree) => {
    expect(listDirNames(tree)).toEqual(SKILLS);
    for (const skill of SKILLS) {
      const canonical = readFileSync(join(REPO_ROOT, 'skills', skill, 'SKILL.md'));
      const generated = readFileSync(join(REPO_ROOT, tree, skill, 'SKILL.md'));
      expect(generated.equals(canonical), `${tree}/${skill}/SKILL.md should match skills/`).toBe(true);
    }
  });

  it('sync-agent-assets --check passes (no manual drift)', () => {
    // The whole point of the generator: catch a hand-edited copy in CI instead of
    // shipping two different sets of instructions to two different agents.
    expect(() =>
      execFileSync('node', ['scripts/sync-agent-assets.mjs', '--check'], {
        cwd: REPO_ROOT,
        stdio: 'pipe',
      }),
    ).not.toThrow();
  });
});

describe('rules', () => {
  const RULES = ['sprang-context.md', 'sprang-dashboard.md', 'sprang-highrisk.md'].sort();

  it('.devin/rules/ holds the canonical rules and .claude/rules mirrors them', () => {
    expect(listDirNames('.devin/rules')).toEqual(RULES);
    expect(listDirNames('.claude/rules')).toEqual(RULES);
    for (const rule of RULES) {
      const devin = readFileSync(join(REPO_ROOT, '.devin/rules', rule));
      const claude = readFileSync(join(REPO_ROOT, '.claude/rules', rule));
      expect(claude.equals(devin), `${rule} should be byte-identical`).toBe(true);
    }
  });

  it('every rule declares a trigger', () => {
    for (const rule of RULES) {
      const content = readFileSync(join(REPO_ROOT, '.devin/rules', rule), 'utf-8');
      const fm = parseFrontmatter(content);
      expect(fm, `${rule} frontmatter`).not.toBeNull();
      expect(
        ['always_on', 'manual', 'model_decision', 'agent', 'glob'],
        `${rule} trigger`,
      ).toContain(fm!['trigger']);
    }
  });

  it('the context rule is glob-scoped rather than always-on', () => {
    // Devin's guidance: keep always-on context minimal, prefer targeted triggers.
    const fm = parseFrontmatter(readFileSync(join(REPO_ROOT, '.devin/rules/sprang-context.md'), 'utf-8'));
    expect(fm!['trigger']).toBe('glob');
    expect(Array.isArray(fm!['globs'])).toBe(true);
  });
});

describe('hooks wiring', () => {
  const HOOK_SCRIPTS = ['session-start.sh', 'post-tool-use.sh', 'stop-dashboard-question.sh', 'user-prompt-dashboard-question.sh'];

  it('.devin/hooks.v1.json registers SessionStart and PostToolUse', () => {
    // The pre-0.3 file used `post_cascade_response_with_transcript`, an event no
    // current runtime fires — so the hook silently never ran.
    const config = readJson('.devin/hooks.v1.json');
    expect(config.post_cascade_response_with_transcript).toBeUndefined();
    for (const event of ['SessionStart', 'PostToolUse', 'Stop', 'UserPromptSubmit']) {
      expect(Array.isArray(config[event]), `${event} array`).toBe(true);
      expect(config[event][0].hooks[0].command, `${event} command`).toContain('.devin/hooks/');
    }
  });

  it('.claude/settings.json wires the same two events', () => {
    const settings = readJson('.claude/settings.json');
    for (const event of ['SessionStart', 'PostToolUse']) {
      expect(Array.isArray(settings.hooks[event]), `${event} array`).toBe(true);
      expect(settings.hooks[event][0].hooks[0].command, `${event} command`).toContain('.claude/hooks/');
    }
  });

  it.each(HOOK_SCRIPTS)('%s exists and is executable in both trees', (script) => {
    for (const dir of ['.devin/hooks', '.claude/hooks']) {
      const path = join(REPO_ROOT, dir, script);
      expect(existsSync(path), `${dir}/${script} should exist`).toBe(true);
      expect(statSync(path).mode & 0o111, `${dir}/${script} should be executable`).not.toBe(0);
    }
  });

  it('hook scripts read the payload from stdin, not a TOOL_INPUT env var', () => {
    // Both Devin and Claude deliver hook events as JSON on stdin. Reading
    // $TOOL_INPUT (as v0.2.x did) always yielded an empty string, so the
    // git-commit auto-refresh never fired even though its tests passed.
    const content = readFileSync(join(REPO_ROOT, '.devin/hooks/post-tool-use.sh'), 'utf-8');
    expect(content).toContain('tool_input');
    expect(content).toMatch(/PAYLOAD=\$\(cat/);
  });
});

describe('copilot extras', () => {
  it('.github/copilot-instructions.md mentions all 9 MCP tools', () => {
    const path = join(REPO_ROOT, '.github/copilot-instructions.md');
    expect(existsSync(path)).toBe(true);
    const content = readFileSync(path, 'utf-8');
    for (const tool of MCP_TOOLS) {
      expect(content, `copilot-instructions should mention ${tool}`).toContain(tool);
    }
  });
});
